### ISSUE TITLE
On mobile devices, the titles of milestone children (sub-points) have bigger font size than the main milestone points.

### ISSUE THREAD

**Issue by masterde** [iBiziness/iBusiness.sa#23]

**Comment by AngeloAballe** [comment]
Fixed.

**Comment by masterde** [comment]
It's still there, the second child of the milestone is is still significantly bigger than the rest, it seems that on mobile devices h4 is bigger than h3 and h2, let's reverse it.

**Comment by AngeloAballe** [comment]
My bad. I missed the h4 tag. I made a commit that fixes this.
